### ISSUE TITLE
A primeira issue - Criar um readme. 

### ISSUE THREAD

**Issue by gabicantarini** [WilliamFischdick/Sunnyside#1]
Como recomendações é possível adicionar mais informações, mais detalhes do projeto, o que você aprendeu com ele, quais foram as dificuldades, adicionar badges e ser criativo para adicionar mais do seu estilo. :white_check_mark:

**Comment by WilliamFischdick** [comment]
Muito Obrigado pelo feedback, vou seguir com as dicas!
